apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbitalpulse-collector
  namespace: default
  labels:
    app: orbitalpulse-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbitalpulse-collector
  template:
    metadata:
      labels:
        app: orbitalpulse-collector
    spec:
      containers:
        - name: collector
          image: orbitalpulse_collector:latest
          imagePullPolicy: Never
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: orbitalpulse-db-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: orbitalpulse-db-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: orbitalpulse-db-secret
                  key: POSTGRES_DB