apiVersion: v1
kind: Secret
metadata:
  name: orbitalpulse-db-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: aWFtZ3Jvb3Q=          # Encodage base64 de ton user
  POSTGRES_PASSWORD: aWFtZ3Jvb3Q5MzQyMA==  # Encodage base64 de ton password
  POSTGRES_DB: b3JiaXRhbHB1bHNl         # Encodage base64 de ton nom de DB
  DB_PORT: NTQzMg==                   # Encodage base64 du port (5432)
  CESIUM_TOKEN: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnViMjVqWlNJNklqVkJhR2xTUlc5QlMzVmFSR0p0U21NaUxDSnFkR2tpT2lJeU5XVmlaR1F4TVMwME9HUTNMVFExTldVdE9EWXdOQzFpTkRFMk9XUmxPVFJpWTJZaUxDSnBaQ0k2TkRrMk1USTVMQ0pwYzNNaU9pSm9kSFJ3Y3pvdkwyRndhUzVqWlhOcGRXMHVZMjl0SWl3aVlYVmtJam9pZFc1a1pXWnBibVZrWDJSbFptRjFiSFFpTENKcFlYUWlPakUzT0RrMU1ESTBOamQ5LlRzNGt6RGE0cmllM0NmMTRqdTdKMENqcUdycXVFdWlPSmFaOW5DSldFMjg=                       

