apiVersion: v1
kind: Secret
metadata:
  name: orbitalpulse-db-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: aWFtZ3Jvb3Q=          # Encodage base64 de ton user
  POSTGRES_PASSWORD: aWFtZ3Jvb3Q5MzQyMA==  # Encodage base64 de ton password
  POSTGRES_DB: b3JiaXRhbHB1bHNl         # Encodage base64 de ton nom de DB
  DB_PORT: NTQzMg==                   # Encodage base64 du port (5432)