apiVersion: v1
kind: Secret
metadata:
  name: orbitalpulse-db-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: <base64_user>
  POSTGRES_PASSWORD: <base64_password>
  POSTGRES_DB: <base64_db>
  DB_PORT: <base64_port>