CREATE TABLE IF NOT EXISTS iss_telemetry (
    id SERIAL PRIMARY KEY,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    altitude DOUBLE PRECISION NOT NULL,
    velocity DOUBLE PRECISION NOT NULL,
    visibility VARCHAR(50),
    captured_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);